version: '3.8'
services:
  # PostgreSQL Database Service
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: TechFest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /c/Users/shaur/Desktop:/db_backup

  # Spring Boot Application Service
  app:
    build:
      context: ./event-service/event-service
      dockerfile: Dockerfile
    container_name: Tech-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/TechFest
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  # Auth Service (Spring Boot)
  auth-service:
    build:
      context: "./Authentication-Service/Authentication-Service"
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"

  # React Frontend
  react-app:
    build:
      context: "./frontend/Techfest2"
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "5173:5173"

volumes:
  postgres_data:
